### ISSUE TITLE
No way to make the glass shatter when broken

### ISSUE THREAD

**Issue by Winddbourne** [kreezxil/diamondglass#7]
I was looking for a hard material that shattered like glass when broken and your mod was a perfect candidate . . . Diamond glass. Unfortunately, the glass drops when harvested with a diamond pickaxe and there is no setting to make it require silk touch. 

My concept was to use some of your glass to replace the bedrock placed by the hardcore spelunking mod so that I'd have a material that was extremely hard to dig through, and dropped nothing when mined unless you had silk touch. 

That would have allowed me to create an adventure dimension where players were encouraged to explore caves, dungeons, and mineshafts without strip mining; but if they got stuck due to procedural generation they could dig through if they had to . . . very slowly.

**Comment by kreezxil** [comment]
I started this way back in 1.8 when extra utilities had not yet ported up
from 1.7.10 and i wanted glass that was hard and clear like the glass from
that mod. I've kept with that concept ever since.

**However**, because this mod has configs, I'll see what I can do about
adding the features you're requesting via configs.

**Comment by kreezxil** [comment]
however, I never wanted this glass to shatter either.
